const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      images: "/images/P1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 5,
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      images: "/images/P2.jpg",
      price: 100,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      images: "/images/P3.jpg",
      price: 220,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Shirts",
      images: "/images/P4.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
      countInStock: 1,
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      images: "/images/P5.jpg",
      price: 65,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      images: "/images/P6.jpg",
      price: 139,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      countInStock: 3,
    },
  ],
};
export default data;
